export const STUDENT_DATABASE = {
  "25G01A4301": {
    rollNumber: "25G01A4301",
    name: "A B SURESH",
    branch: "Artificial Intelligence (AI)",
    yearSem: "B.Tech I Year - I Semester",
    regulation: "R23",
    college: "Sri Venkatesa Perumal College of Engineering & Technology (AUTONOMOUS)",
    status: "FAILED",
    sgpa: 4.03,
    cgpa: 4.03,
    subjects: [
      { code: "23HM0001", name: "COMMUNICATIVE ENGLISH", credits: 0, grade: "F", status: "FAIL" },
      { code: "23BS0005", name: "CHEMISTRY", credits: 3, grade: "E", status: "PASS" },
      { code: "23BS0001", name: "LINEAR ALGEBRA & CALCULUS", credits: 3, grade: "E", status: "PASS" },
      { code: "23ES0101", name: "BASIC CIVIL & MECHANICAL ENGINEERING", credits: 3, grade: "D", status: "PASS" },
      { code: "23ES0501", name: "INTRODUCTION TO PROGRAMMING", credits: 0, grade: "F", status: "FAIL" },
      { code: "23LC0001", name: "COMMUNICATIVE ENGLISH LAB", credits: 1, grade: "C", status: "PASS" },
      { code: "23LC0004", name: "CHEMISTRY LAB", credits: 1, grade: "D", status: "PASS" },
      { code: "23LC0301", name: "ENGINEERING WORKSHOP", credits: 1.5, grade: "A", status: "PASS" },
      { code: "23LC0501", name: "COMPUTER PROGRAMMING LAB", credits: 0, grade: "-Ab-", status: "FAIL" },
      { code: "23HM0002", name: "HEALTH AND WELLNESS, YOGA AND SPORTS", credits: 0.5, grade: "B", status: "PASS" }
    ]
  },
  "25G01A4302": {
    rollNumber: "25G01A4302",
    name: "A G JAMUNA",
    branch: "Artificial Intelligence (AI)",
    yearSem: "B.Tech I Year - I Semester",
    regulation: "R23",
    college: "Sri Venkatesa Perumal College of Engineering & Technology (AUTONOMOUS)",
    status: "PASSED",
    sgpa: 7.69,
    cgpa: 7.69,
    subjects: [
      { code: "23HM0001", name: "COMMUNICATIVE ENGLISH", credits: 2, grade: "C", status: "PASS" },
      { code: "23BS0005", name: "CHEMISTRY", credits: 3, grade: "C", status: "PASS" },
      { code: "23BS0001", name: "LINEAR ALGEBRA & CALCULUS", credits: 3, grade: "B", status: "PASS" },
      { code: "23ES0101", name: "BASIC CIVIL & MECHANICAL ENGINEERING", credits: 3, grade: "B", status: "PASS" },
      { code: "23ES0501", name: "INTRODUCTION TO PROGRAMMING", credits: 3, grade: "D", status: "PASS" },
      { code: "23LC0001", name: "COMMUNICATIVE ENGLISH LAB", credits: 1, grade: "A", status: "PASS" },
      { code: "23LC0004", name: "CHEMISTRY LAB", credits: 1, grade: "S", status: "PASS" },
      { code: "23LC0301", name: "ENGINEERING WORKSHOP", credits: 1.5, grade: "A", status: "PASS" },
      { code: "23LC0501", name: "COMPUTER PROGRAMMING LAB", credits: 1.5, grade: "B", status: "PASS" },
      { code: "23HM0002", name: "HEALTH AND WELLNESS, YOGA AND SPORTS", credits: 0.5, grade: "A", status: "PASS" }
    ]
  },
  "25G01A4303": {
    rollNumber: "25G01A4303",
    name: "A M DHANUSH",
    branch: "Artificial Intelligence (AI)",
    yearSem: "B.Tech I Year - I Semester",
    regulation: "R23",
    college: "Sri Venkatesa Perumal College of Engineering & Technology (AUTONOMOUS)",
    status: "FAILED",
    sgpa: 3.79,
    cgpa: 3.79,
    subjects: [
      { code: "23HM0001", name: "COMMUNICATIVE ENGLISH", credits: 0, grade: "F", status: "FAIL" },
      { code: "23BS0005", name: "CHEMISTRY", credits: 3, grade: "E", status: "PASS" },
      { code: "23BS0001", name: "LINEAR ALGEBRA & CALCULUS", credits: 3, grade: "D", status: "PASS" },
      { code: "23ES0101", name: "BASIC CIVIL & MECHANICAL ENGINEERING", credits: 0, grade: "F", status: "FAIL" },
      { code: "23ES0501", name: "INTRODUCTION TO PROGRAMMING", credits: 0, grade: "F", status: "FAIL" },
      { code: "23LC0001", name: "COMMUNICATIVE ENGLISH LAB", credits: 1, grade: "C", status: "PASS" },
      { code: "23LC0004", name: "CHEMISTRY LAB", credits: 1, grade: "C", status: "PASS" },
      { code: "23LC0301", name: "ENGINEERING WORKSHOP", credits: 1.5, grade: "A", status: "PASS" },
      { code: "23LC0501", name: "COMPUTER PROGRAMMING LAB", credits: 1.5, grade: "D", status: "PASS" },
      { code: "23HM0002", name: "HEALTH AND WELLNESS, YOGA AND SPORTS", credits: 0.5, grade: "A", status: "PASS" }
    ]
  },
  "25G01A4304": {
    rollNumber: "25G01A4304",
    name: "A P YAMINI",
    branch: "Artificial Intelligence (AI)",
    yearSem: "B.Tech I Year - I Semester",
    regulation: "R23",
    college: "Sri Venkatesa Perumal College of Engineering & Technology (AUTONOMOUS)",
    status: "PASSED",
    sgpa: 7.69,
    cgpa: 7.69,
    subjects: [
      { code: "23HM0001", name: "COMMUNICATIVE ENGLISH", credits: 2, grade: "B", status: "PASS" },
      { code: "23BS0005", name: "CHEMISTRY", credits: 3, grade: "B", status: "PASS" },
      { code: "23BS0001", name: "LINEAR ALGEBRA & CALCULUS", credits: 3, grade: "D", status: "PASS" },
      { code: "23ES0101", name: "BASIC CIVIL & MECHANICAL ENGINEERING", credits: 3, grade: "C", status: "PASS" },
      { code: "23ES0501", name: "INTRODUCTION TO PROGRAMMING", credits: 3, grade: "C", status: "PASS" },
      { code: "23LC0001", name: "COMMUNICATIVE ENGLISH LAB", credits: 1, grade: "A", status: "PASS" },
      { code: "23LC0004", name: "CHEMISTRY LAB", credits: 1, grade: "A", status: "PASS" },
      { code: "23LC0301", name: "ENGINEERING WORKSHOP", credits: 1.5, grade: "S", status: "PASS" },
      { code: "23LC0501", name: "COMPUTER PROGRAMMING LAB", credits: 1.5, grade: "B", status: "PASS" },
      { code: "23HM0002", name: "HEALTH AND WELLNESS, YOGA AND SPORTS", credits: 0.5, grade: "S", status: "PASS" }
    ]
  },
  "25G01A4305": {
    rollNumber: "25G01A4305",
    name: "A PREETHI",
    branch: "Artificial Intelligence (AI)",
    yearSem: "B.Tech I Year - I Semester",
    regulation: "R23",
    college: "Sri Venkatesa Perumal College of Engineering & Technology (AUTONOMOUS)",
    status: "FAILED",
    sgpa: 3.00,
    cgpa: 3.00,
    subjects: [
      { code: "23HM0001", name: "COMMUNICATIVE ENGLISH", credits: 2, grade: "D", status: "PASS" },
      { code: "23BS0005", name: "CHEMISTRY", credits: 0, grade: "F", status: "FAIL" },
      { code: "23BS0001", name: "LINEAR ALGEBRA & CALCULUS", credits: 0, grade: "F", status: "FAIL" },
      { code: "23ES0101", name: "BASIC CIVIL & MECHANICAL ENGINEERING", credits: 0, grade: "F", status: "FAIL" },
      { code: "23ES0501", name: "INTRODUCTION TO PROGRAMMING", credits: 0, grade: "F", status: "FAIL" },
      { code: "23LC0001", name: "COMMUNICATIVE ENGLISH LAB", credits: 1, grade: "A", status: "PASS" },
      { code: "23LC0004", name: "CHEMISTRY LAB", credits: 1, grade: "A", status: "PASS" },
      { code: "23LC0301", name: "ENGINEERING WORKSHOP", credits: 1.5, grade: "A", status: "PASS" },
      { code: "23LC0501", name: "COMPUTER PROGRAMMING LAB", credits: 1.5, grade: "C", status: "PASS" },
      { code: "23HM0002", name: "HEALTH AND WELLNESS, YOGA AND SPORTS", credits: 0.5, grade: "A", status: "PASS" }
    ]
  },
  "25G01A4306": {
    rollNumber: "25G01A4306",
    name: "A VISHNUVARDHAN",
    branch: "Artificial Intelligence (AI)",
    yearSem: "B.Tech I Year - I Semester",
    regulation: "R23",
    college: "Sri Venkatesa Perumal College of Engineering & Technology (AUTONOMOUS)",
    status: "PASSED",
    sgpa: 7.82,
    cgpa: 7.82,
    subjects: [
      { code: "23HM0001", name: "COMMUNICATIVE ENGLISH", credits: 2, grade: "C", status: "PASS" },
      { code: "23BS0005", name: "CHEMISTRY", credits: 3, grade: "B", status: "PASS" },
      { code: "23BS0001", name: "LINEAR ALGEBRA & CALCULUS", credits: 3, grade: "B", status: "PASS" },
      { code: "23ES0101", name: "BASIC CIVIL & MECHANICAL ENGINEERING", credits: 3, grade: "B", status: "PASS" },
      { code: "23ES0501", name: "INTRODUCTION TO PROGRAMMING", credits: 3, grade: "D", status: "PASS" },
      { code: "23LC0001", name: "COMMUNICATIVE ENGLISH LAB", credits: 1, grade: "B", status: "PASS" },
      { code: "23LC0004", name: "CHEMISTRY LAB", credits: 1, grade: "A", status: "PASS" },
      { code: "23LC0301", name: "ENGINEERING WORKSHOP", credits: 1.5, grade: "S", status: "PASS" },
      { code: "23LC0501", name: "COMPUTER PROGRAMMING LAB", credits: 1.5, grade: "B", status: "PASS" },
      { code: "23HM0002", name: "HEALTH AND WELLNESS, YOGA AND SPORTS", credits: 0.5, grade: "A", status: "PASS" }
    ]
  },
  "25G01A4307": {
    rollNumber: "25G01A4307",
    name: "AAVULA DHARANI YADAV",
    branch: "Artificial Intelligence (AI)",
    yearSem: "B.Tech I Year - I Semester",
    regulation: "R23",
    college: "Sri Venkatesa Perumal College of Engineering & Technology (AUTONOMOUS)",
    status: "PASSED",
    sgpa: 8.85,
    cgpa: 8.85,
    subjects: [
      { code: "23HM0001", name: "COMMUNICATIVE ENGLISH", credits: 2, grade: "A", status: "PASS" },
      { code: "23BS0005", name: "CHEMISTRY", credits: 3, grade: "A", status: "PASS" },
      { code: "23BS0001", name: "LINEAR ALGEBRA & CALCULUS", credits: 3, grade: "A", status: "PASS" },
      { code: "23ES0101", name: "BASIC CIVIL & MECHANICAL ENGINEERING", credits: 3, grade: "B", status: "PASS" },
      { code: "23ES0501", name: "INTRODUCTION TO PROGRAMMING", credits: 3, grade: "B", status: "PASS" },
      { code: "23LC0001", name: "COMMUNICATIVE ENGLISH LAB", credits: 1, grade: "A", status: "PASS" },
      { code: "23LC0004", name: "CHEMISTRY LAB", credits: 1, grade: "S", status: "PASS" },
      { code: "23LC0301", name: "ENGINEERING WORKSHOP", credits: 1.5, grade: "S", status: "PASS" },
      { code: "23LC0501", name: "COMPUTER PROGRAMMING LAB", credits: 1.5, grade: "A", status: "PASS" },
      { code: "23HM0002", name: "HEALTH AND WELLNESS, YOGA AND SPORTS", credits: 0.5, grade: "S", status: "PASS" }
    ]
  },
  "25G01A4310": {
    rollNumber: "25G01A4310",
    name: "ANDHI NAGA PRANATHI",
    branch: "Artificial Intelligence (AI)",
    yearSem: "B.Tech I Year - I Semester",
    regulation: "R23",
    college: "Sri Venkatesa Perumal College of Engineering & Technology (AUTONOMOUS)",
    status: "PASSED",
    sgpa: 7.26,
    cgpa: 7.26,
    subjects: [
      { code: "23HM0001", name: "COMMUNICATIVE ENGLISH", credits: 2, grade: "B", status: "PASS" },
      { code: "23BS0005", name: "CHEMISTRY", credits: 3, grade: "C", status: "PASS" },
      { code: "23BS0001", name: "LINEAR ALGEBRA & CALCULUS", credits: 3, grade: "D", status: "PASS" },
      { code: "23ES0101", name: "BASIC CIVIL & MECHANICAL ENGINEERING", credits: 3, grade: "C", status: "PASS" },
      { code: "23ES0501", name: "INTRODUCTION TO PROGRAMMING", credits: 3, grade: "D", status: "PASS" },
      { code: "23LC0001", name: "COMMUNICATIVE ENGLISH LAB", credits: 1, grade: "A", status: "PASS" },
      { code: "23LC0004", name: "CHEMISTRY LAB", credits: 1, grade: "S", status: "PASS" },
      { code: "23LC0301", name: "ENGINEERING WORKSHOP", credits: 1.5, grade: "B", status: "PASS" },
      { code: "23LC0501", name: "COMPUTER PROGRAMMING LAB", credits: 1.5, grade: "B", status: "PASS" },
      { code: "23HM0002", name: "HEALTH AND WELLNESS, YOGA AND SPORTS", credits: 0.5, grade: "A", status: "PASS" }
    ]
  },
  "25G01A4311": {
    rollNumber: "25G01A4311",
    name: "ANGITEELA BHAVANA",
    branch: "Artificial Intelligence (AI)",
    yearSem: "B.Tech I Year - I Semester",
    regulation: "R23",
    college: "Sri Venkatesa Perumal College of Engineering & Technology (AUTONOMOUS)",
    status: "FAILED",
    sgpa: 6.59,
    cgpa: 6.59,
    subjects: [
      { code: "23HM0001", name: "COMMUNICATIVE ENGLISH", credits: 2, grade: "A", status: "PASS" },
      { code: "23BS0005", name: "CHEMISTRY", credits: 3, grade: "C", status: "PASS" },
      { code: "23BS0001", name: "LINEAR ALGEBRA & CALCULUS", credits: 0, grade: "F", status: "FAIL" },
      { code: "23ES0101", name: "BASIC CIVIL & MECHANICAL ENGINEERING", credits: 3, grade: "C", status: "PASS" },
      { code: "23ES0501", name: "INTRODUCTION TO PROGRAMMING", credits: 3, grade: "C", status: "PASS" },
      { code: "23LC0001", name: "COMMUNICATIVE ENGLISH LAB", credits: 1, grade: "A", status: "PASS" },
      { code: "23LC0004", name: "CHEMISTRY LAB", credits: 1, grade: "S", status: "PASS" },
      { code: "23LC0301", name: "ENGINEERING WORKSHOP", credits: 1.5, grade: "A", status: "PASS" },
      { code: "23LC0501", name: "COMPUTER PROGRAMMING LAB", credits: 1.5, grade: "C", status: "PASS" },
      { code: "23HM0002", name: "HEALTH AND WELLNESS, YOGA AND SPORTS", credits: 0.5, grade: "A", status: "PASS" }
    ]
  },
  "25G01A4312": {
    rollNumber: "25G01A4312",
    name: "ARAVA SOUJANYA",
    branch: "Artificial Intelligence (AI)",
    yearSem: "B.Tech I Year - I Semester",
    regulation: "R23",
    college: "Sri Venkatesa Perumal College of Engineering & Technology (AUTONOMOUS)",
    status: "FAILED",
    sgpa: 0,
    cgpa: 0,
    subjects: [
      { code: "23HM0001", name: "COMMUNICATIVE ENGLISH", credits: 2, grade: "B", status: "PASS" },
      { code: "23BS0005", name: "CHEMISTRY", credits: 3, grade: "D", status: "PASS" },
      { code: "23BS0001", name: "LINEAR ALGEBRA & CALCULUS", credits: 0, grade: "F", status: "FAIL" },
      { code: "23ES0101", name: "BASIC CIVIL & MECHANICAL ENGINEERING", credits: 3, grade: "B", status: "PASS" },
      { code: "23ES0501", name: "INTRODUCTION TO PROGRAMMING", credits: 3, grade: "C", status: "PASS" },
      { code: "23LC0001", name: "COMMUNICATIVE ENGLISH LAB", credits: 1, grade: "A", status: "PASS" },
      { code: "23LC0004", name: "CHEMISTRY LAB", credits: 1, grade: "S", status: "PASS" },
      { code: "23LC0301", name: "ENGINEERING WORKSHOP", credits: 1.5, grade: "A", status: "PASS" },
      { code: "23LC0501", name: "COMPUTER PROGRAMMING LAB", credits: 1.5, grade: "B", status: "PASS" },
      { code: "23HM0002", name: "HEALTH AND WELLNESS, YOGA AND SPORTS", credits: 0.5, grade: "S", status: "PASS" }
    ]
  },
  "25G01A4313": {
    rollNumber: "25G01A4313",
    name: "ARDHAMALA SASI KUMAR",
    branch: "Artificial Intelligence (AI)",
    yearSem: "B.Tech I Year - I Semester",
    regulation: "R23",
    college: "Sri Venkatesa Perumal College of Engineering & Technology (AUTONOMOUS)",
    status: "FAILED",
    sgpa: 2.72,
    cgpa: 2.72,
    subjects: [
      { code: "23HM0001", name: "COMMUNICATIVE ENGLISH", credits: 0, grade: "F", status: "FAIL" },
      { code: "23BS0005", name: "CHEMISTRY", credits: 3, grade: "E", status: "PASS" },
      { code: "23BS0001", name: "LINEAR ALGEBRA & CALCULUS", credits: 0, grade: "F", status: "FAIL" },
      { code: "23ES0101", name: "BASIC CIVIL & MECHANICAL ENGINEERING", credits: 0, grade: "F", status: "FAIL" },
      { code: "23ES0501", name: "INTRODUCTION TO PROGRAMMING", credits: 0, grade: "F", status: "FAIL" },
      { code: "23LC0001", name: "COMMUNICATIVE ENGLISH LAB", credits: 1, grade: "C", status: "PASS" },
      { code: "23LC0004", name: "CHEMISTRY LAB", credits: 1, grade: "C", status: "PASS" },
      { code: "23LC0301", name: "ENGINEERING WORKSHOP", credits: 1.5, grade: "B", status: "PASS" },
      { code: "23LC0501", name: "COMPUTER PROGRAMMING LAB", credits: 1.5, grade: "E", status: "PASS" },
      { code: "23HM0002", name: "HEALTH AND WELLNESS, YOGA AND SPORTS", credits: 0.5, grade: "A", status: "PASS" }
    ]
  },
  "25G01A4314": {
    rollNumber: "25G01A4314",
    name: "ATTUKARA YAGNITHA",
    branch: "Artificial Intelligence (AI)",
    yearSem: "B.Tech I Year - I Semester",
    regulation: "R23",
    college: "Sri Venkatesa Perumal College of Engineering & Technology (AUTONOMOUS)",
    status: "PASSED",
    sgpa: 8.36,
    cgpa: 8.36,
    subjects: [
      { code: "23HM0001", name: "COMMUNICATIVE ENGLISH", credits: 2, grade: "S", status: "PASS" },
      { code: "23BS0005", name: "CHEMISTRY", credits: 3, grade: "B", status: "PASS" },
      { code: "23BS0001", name: "LINEAR ALGEBRA & CALCULUS", credits: 3, grade: "B", status: "PASS" },
      { code: "23ES0101", name: "BASIC CIVIL & MECHANICAL ENGINEERING", credits: 3, grade: "C", status: "PASS" },
      { code: "23ES0501", name: "INTRODUCTION TO PROGRAMMING", credits: 3, grade: "C", status: "PASS" },
      { code: "23LC0001", name: "COMMUNICATIVE ENGLISH LAB", credits: 1, grade: "S", status: "PASS" },
      { code: "23LC0004", name: "CHEMISTRY LAB", credits: 1, grade: "S", status: "PASS" },
      { code: "23LC0301", name: "ENGINEERING WORKSHOP", credits: 1.5, grade: "S", status: "PASS" },
      { code: "23LC0501", name: "COMPUTER PROGRAMMING LAB", credits: 1.5, grade: "A", status: "PASS" },
      { code: "23HM0002", name: "HEALTH AND WELLNESS, YOGA AND SPORTS", credits: 0.5, grade: "A", status: "PASS" }
    ]
  },
  "25G01A4315": {
    rollNumber: "25G01A4315",
    name: "AYYAPPA YUVANSANKAR",
    branch: "Artificial Intelligence (AI)",
    yearSem: "B.Tech I Year - I Semester",
    regulation: "R23",
    college: "Sri Venkatesa Perumal College of Engineering & Technology (AUTONOMOUS)",
    status: "FAILED",
    sgpa: 3.92,
    cgpa: 3.92,
    subjects: [
      { code: "23HM0001", name: "COMMUNICATIVE ENGLISH", credits: 0, grade: "F", status: "FAIL" },
      { code: "23BS0005", name: "CHEMISTRY", credits: 3, grade: "E", status: "PASS" },
      { code: "23BS0001", name: "LINEAR ALGEBRA & CALCULUS", credits: 3, grade: "D", status: "PASS" },
      { code: "23ES0101", name: "BASIC CIVIL & MECHANICAL ENGINEERING", credits: 0, grade: "F", status: "FAIL" },
      { code: "23ES0501", name: "INTRODUCTION TO PROGRAMMING", credits: 0, grade: "F", status: "FAIL" },
      { code: "23LC0001", name: "COMMUNICATIVE ENGLISH LAB", credits: 1, grade: "C", status: "PASS" },
      { code: "23LC0004", name: "CHEMISTRY LAB", credits: 1, grade: "B", status: "PASS" },
      { code: "23LC0301", name: "ENGINEERING WORKSHOP", credits: 1.5, grade: "B", status: "PASS" },
      { code: "23LC0501", name: "COMPUTER PROGRAMMING LAB", credits: 1.5, grade: "B", status: "PASS" },
      { code: "23HM0002", name: "HEALTH AND WELLNESS, YOGA AND SPORTS", credits: 0.5, grade: "A", status: "PASS" }
    ]
  },
  "25G01A4316": {
    rollNumber: "25G01A4316",
    name: "B JHANSI",
    branch: "Artificial Intelligence (AI)",
    yearSem: "B.Tech I Year - I Semester",
    regulation: "R23",
    college: "Sri Venkatesa Perumal College of Engineering & Technology (AUTONOMOUS)",
    status: "FAILED",
    sgpa: 3.03,
    cgpa: 3.03,
    subjects: [
      { code: "23HM0001", name: "COMMUNICATIVE ENGLISH", credits: 0, grade: "F", status: "FAIL" },
      { code: "23BS0005", name: "CHEMISTRY", credits: 3, grade: "E", status: "PASS" },
      { code: "23BS0001", name: "LINEAR ALGEBRA & CALCULUS", credits: 0, grade: "F", status: "FAIL" },
      { code: "23ES0101", name: "BASIC CIVIL & MECHANICAL ENGINEERING", credits: 0, grade: "F", status: "FAIL" },
      { code: "23ES0501", name: "INTRODUCTION TO PROGRAMMING", credits: 0, grade: "F", status: "FAIL" },
      { code: "23LC0001", name: "COMMUNICATIVE ENGLISH LAB", credits: 1, grade: "B", status: "PASS" },
      { code: "23LC0004", name: "CHEMISTRY LAB", credits: 1, grade: "C", status: "PASS" },
      { code: "23LC0301", name: "ENGINEERING WORKSHOP", credits: 1.5, grade: "A", status: "PASS" },
      { code: "23LC0501", name: "COMPUTER PROGRAMMING LAB", credits: 1.5, grade: "C", status: "PASS" },
      { code: "23HM0002", name: "HEALTH AND WELLNESS, YOGA AND SPORTS", credits: 0.5, grade: "S", status: "PASS" }
    ]
  },
  "25G01A4317": {
    rollNumber: "25G01A4317",
    name: "B SHALINI",
    branch: "Artificial Intelligence (AI)",
    yearSem: "B.Tech I Year - I Semester",
    regulation: "R23",
    college: "Sri Venkatesa Perumal College of Engineering & Technology (AUTONOMOUS)",
    status: "FAILED",
    sgpa: 4.38,
    cgpa: 4.38,
    subjects: [
      { code: "23HM0001", name: "COMMUNICATIVE ENGLISH", credits: 2, grade: "D", status: "PASS" },
      { code: "23BS0005", name: "CHEMISTRY", credits: 3, grade: "E", status: "PASS" },
      { code: "23BS0001", name: "LINEAR ALGEBRA & CALCULUS", credits: 3, grade: "E", status: "PASS" },
      { code: "23ES0101", name: "BASIC CIVIL & MECHANICAL ENGINEERING", credits: 0, grade: "F", status: "FAIL" },
      { code: "23ES0501", name: "INTRODUCTION TO PROGRAMMING", credits: 0, grade: "F", status: "FAIL" },
      { code: "23LC0001", name: "COMMUNICATIVE ENGLISH LAB", credits: 1, grade: "B", status: "PASS" },
      { code: "23LC0004", name: "CHEMISTRY LAB", credits: 1, grade: "C", status: "PASS" },
      { code: "23LC0301", name: "ENGINEERING WORKSHOP", credits: 1.5, grade: "A", status: "PASS" },
      { code: "23LC0501", name: "COMPUTER PROGRAMMING LAB", credits: 1.5, grade: "C", status: "PASS" },
      { code: "23HM0002", name: "HEALTH AND WELLNESS, YOGA AND SPORTS", credits: 0.5, grade: "A", status: "PASS" }
    ]
  },
  "25G01A4318": {
    rollNumber: "25G01A4318",
    name: "B THIRUMALESU",
    branch: "Artificial Intelligence (AI)",
    yearSem: "B.Tech I Year - I Semester",
    regulation: "R23",
    college: "Sri Venkatesa Perumal College of Engineering & Technology (AUTONOMOUS)",
    status: "FAILED",
    sgpa: 1.95,
    cgpa: 1.95,
    subjects: [
      { code: "23HM0001", name: "COMMUNICATIVE ENGLISH", credits: 0, grade: "F", status: "FAIL" },
      { code: "23BS0005", name: "CHEMISTRY", credits: 0, grade: "F", status: "FAIL" },
      { code: "23BS0001", name: "LINEAR ALGEBRA & CALCULUS", credits: 0, grade: "F", status: "FAIL" },
      { code: "23ES0101", name: "BASIC CIVIL & MECHANICAL ENGINEERING", credits: 0, grade: "F", status: "FAIL" },
      { code: "23ES0501", name: "INTRODUCTION TO PROGRAMMING", credits: 0, grade: "F", status: "FAIL" },
      { code: "23LC0001", name: "COMMUNICATIVE ENGLISH LAB", credits: 1, grade: "C", status: "PASS" },
      { code: "23LC0004", name: "CHEMISTRY LAB", credits: 1, grade: "D", status: "PASS" },
      { code: "23LC0301", name: "ENGINEERING WORKSHOP", credits: 1.5, grade: "A", status: "PASS" },
      { code: "23LC0501", name: "COMPUTER PROGRAMMING LAB", credits: 1.5, grade: "E", status: "PASS" },
      { code: "23HM0002", name: "HEALTH AND WELLNESS, YOGA AND SPORTS", credits: 0.5, grade: "B", status: "PASS" }
    ]
  },
  "25G01A4320": {
    rollNumber: "25G01A4320",
    name: "BODIREDDY LOHITHA",
    branch: "Artificial Intelligence (AI)",
    yearSem: "B.Tech I Year - I Semester",
    regulation: "R23",
    college: "Sri Venkatesa Perumal College of Engineering & Technology (AUTONOMOUS)",
    status: "FAILED",
    sgpa: 6.33,
    cgpa: 6.33,
    subjects: [
      { code: "23HM0001", name: "COMMUNICATIVE ENGLISH", credits: 2, grade: "B", status: "PASS" },
      { code: "23BS0005", name: "CHEMISTRY", credits: 3, grade: "D", status: "PASS" },
      { code: "23BS0001", name: "LINEAR ALGEBRA & CALCULUS", credits: 3, grade: "C", status: "PASS" },
      { code: "23ES0101", name: "BASIC CIVIL & MECHANICAL ENGINEERING", credits: 3, grade: "D", status: "PASS" },
      { code: "23ES0501", name: "INTRODUCTION TO PROGRAMMING", credits: 0, grade: "F", status: "FAIL" },
      { code: "23LC0001", name: "COMMUNICATIVE ENGLISH LAB", credits: 1, grade: "S", status: "PASS" },
      { code: "23LC0004", name: "CHEMISTRY LAB", credits: 1, grade: "S", status: "PASS" },
      { code: "23LC0301", name: "ENGINEERING WORKSHOP", credits: 1.5, grade: "S", status: "PASS" },
      { code: "23LC0501", name: "COMPUTER PROGRAMMING LAB", credits: 1.5, grade: "C", status: "PASS" },
      { code: "23HM0002", name: "HEALTH AND WELLNESS, YOGA AND SPORTS", credits: 0.5, grade: "S", status: "PASS" }
    ]
  },
  "25G01A4321": {
    rollNumber: "25G01A4321",
    name: "BORRA LALASA",
    branch: "Artificial Intelligence (AI)",
    yearSem: "B.Tech I Year - I Semester",
    regulation: "R23",
    college: "Sri Venkatesa Perumal College of Engineering & Technology (AUTONOMOUS)",
    status: "PASSED",
    sgpa: 8.64,
    cgpa: 8.64,
    subjects: [
      { code: "23HM0001", name: "COMMUNICATIVE ENGLISH", credits: 2, grade: "B", status: "PASS" },
      { code: "23BS0005", name: "CHEMISTRY", credits: 3, grade: "A", status: "PASS" },
      { code: "23BS0001", name: "LINEAR ALGEBRA & CALCULUS", credits: 3, grade: "S", status: "PASS" },
      { code: "23ES0101", name: "BASIC CIVIL & MECHANICAL ENGINEERING", credits: 3, grade: "C", status: "PASS" },
      { code: "23ES0501", name: "INTRODUCTION TO PROGRAMMING", credits: 3, grade: "C", status: "PASS" },
      { code: "23LC0001", name: "COMMUNICATIVE ENGLISH LAB", credits: 1, grade: "S", status: "PASS" },
      { code: "23LC0004", name: "CHEMISTRY LAB", credits: 1, grade: "S", status: "PASS" },
      { code: "23LC0301", name: "ENGINEERING WORKSHOP", credits: 1.5, grade: "S", status: "PASS" },
      { code: "23LC0501", name: "COMPUTER PROGRAMMING LAB", credits: 1.5, grade: "A", status: "PASS" },
      { code: "23HM0002", name: "HEALTH AND WELLNESS, YOGA AND SPORTS", credits: 0.5, grade: "S", status: "PASS" }
    ]
  },
  "25G01A4322": {
    rollNumber: "25G01A4322",
    name: "BOYA VENU",
    branch: "Artificial Intelligence (AI)",
    yearSem: "B.Tech I Year - I Semester",
    regulation: "R23",
    college: "Sri Venkatesa Perumal College of Engineering & Technology (AUTONOMOUS)",
    status: "FAILED",
    sgpa: 4.38,
    cgpa: 4.38,
    subjects: [
      { code: "23HM0001", name: "COMMUNICATIVE ENGLISH", credits: 2, grade: "C", status: "PASS" },
      { code: "23BS0005", name: "CHEMISTRY", credits: 3, grade: "E", status: "PASS" },
      { code: "23BS0001", name: "LINEAR ALGEBRA & CALCULUS", credits: 3, grade: "E", status: "PASS" },
      { code: "23ES0101", name: "BASIC CIVIL & MECHANICAL ENGINEERING", credits: 0, grade: "F", status: "FAIL" },
      { code: "23ES0501", name: "INTRODUCTION TO PROGRAMMING", credits: 0, grade: "F", status: "FAIL" },
      { code: "23LC0001", name: "COMMUNICATIVE ENGLISH LAB", credits: 1, grade: "C", status: "PASS" },
      { code: "23LC0004", name: "CHEMISTRY LAB", credits: 1, grade: "B", status: "PASS" },
      { code: "23LC0301", name: "ENGINEERING WORKSHOP", credits: 1.5, grade: "A", status: "PASS" },
      { code: "23LC0501", name: "COMPUTER PROGRAMMING LAB", credits: 1.5, grade: "D", status: "PASS" },
      { code: "23HM0002", name: "HEALTH AND WELLNESS, YOGA AND SPORTS", credits: 0.5, grade: "B", status: "PASS" }
    ]
  },
  "25G01A4323": {
    rollNumber: "25G01A4323",
    name: "BUDAGA VINOD",
    branch: "Artificial Intelligence (AI)",
    yearSem: "B.Tech I Year - I Semester",
    regulation: "R23",
    college: "Sri Venkatesa Perumal College of Engineering & Technology (AUTONOMOUS)",
    status: "FAILED",
    sgpa: 3.74,
    cgpa: 3.74,
    subjects: [
      { code: "23HM0001", name: "COMMUNICATIVE ENGLISH", credits: 0, grade: "F", status: "FAIL" },
      { code: "23BS0005", name: "CHEMISTRY", credits: 3, grade: "E", status: "PASS" },
      { code: "23BS0001", name: "LINEAR ALGEBRA & CALCULUS", credits: 3, grade: "E", status: "PASS" },
      { code: "23ES0101", name: "BASIC CIVIL & MECHANICAL ENGINEERING", credits: 0, grade: "F", status: "FAIL" },
      { code: "23ES0501", name: "INTRODUCTION TO PROGRAMMING", credits: 0, grade: "F", status: "FAIL" },
      { code: "23LC0001", name: "COMMUNICATIVE ENGLISH LAB", credits: 1, grade: "C", status: "PASS" },
      { code: "23LC0004", name: "CHEMISTRY LAB", credits: 1, grade: "B", status: "PASS" },
      { code: "23LC0301", name: "ENGINEERING WORKSHOP", credits: 1.5, grade: "A", status: "PASS" },
      { code: "23LC0501", name: "COMPUTER PROGRAMMING LAB", credits: 1.5, grade: "C", status: "PASS" },
      { code: "23HM0002", name: "HEALTH AND WELLNESS, YOGA AND SPORTS", credits: 0.5, grade: "B", status: "PASS" }
    ]
  },
  "25G01A4324": {
    rollNumber: "25G01A4324",
    name: "BUSUPALLI ARUN KUMAR REDDY",
    branch: "Artificial Intelligence (AI)",
    yearSem: "B.Tech I Year - I Semester",
    regulation: "R23",
    college: "Sri Venkatesa Perumal College of Engineering & Technology (AUTONOMOUS)",
    status: "FAILED",
    sgpa: 2.87,
    cgpa: 2.87,
    subjects: [
      { code: "23HM0001", name: "COMMUNICATIVE ENGLISH", credits: 0, grade: "F", status: "FAIL" },
      { code: "23BS0005", name: "CHEMISTRY", credits: 3, grade: "E", status: "PASS" },
      { code: "23BS0001", name: "LINEAR ALGEBRA & CALCULUS", credits: 0, grade: "F", status: "FAIL" },
      { code: "23ES0101", name: "BASIC CIVIL & MECHANICAL ENGINEERING", credits: 0, grade: "F", status: "FAIL" },
      { code: "23ES0501", name: "INTRODUCTION TO PROGRAMMING", credits: 0, grade: "F", status: "FAIL" },
      { code: "23LC0001", name: "COMMUNICATIVE ENGLISH LAB", credits: 1, grade: "C", status: "PASS" },
      { code: "23LC0004", name: "CHEMISTRY LAB", credits: 1, grade: "C", status: "PASS" },
      { code: "23LC0301", name: "ENGINEERING WORKSHOP", credits: 1.5, grade: "A", status: "PASS" },
      { code: "23LC0501", name: "COMPUTER PROGRAMMING LAB", credits: 1.5, grade: "D", status: "PASS" },
      { code: "23HM0002", name: "HEALTH AND WELLNESS, YOGA AND SPORTS", credits: 0.5, grade: "A", status: "PASS" }
    ]
  },
  "25G01A4325": {
    rollNumber: "25G01A4325",
    name: "C DILLI BABU",
    branch: "Artificial Intelligence (AI)",
    yearSem: "B.Tech I Year - I Semester",
    regulation: "R23",
    college: "Sri Venkatesa Perumal College of Engineering & Technology (AUTONOMOUS)",
    status: "FAILED",
    sgpa: 5.26,
    cgpa: 5.26,
    subjects: [
      { code: "23HM0001", name: "COMMUNICATIVE ENGLISH", credits: 2, grade: "D", status: "PASS" },
      { code: "23BS0005", name: "CHEMISTRY", credits: 3, grade: "E", status: "PASS" },
      { code: "23BS0001", name: "LINEAR ALGEBRA & CALCULUS", credits: 0, grade: "F", status: "FAIL" },
      { code: "23ES0101", name: "BASIC CIVIL & MECHANICAL ENGINEERING", credits: 3, grade: "C", status: "PASS" },
      { code: "23ES0501", name: "INTRODUCTION TO PROGRAMMING", credits: 3, grade: "D", status: "PASS" },
      { code: "23LC0001", name: "COMMUNICATIVE ENGLISH LAB", credits: 1, grade: "C", status: "PASS" },
      { code: "23LC0004", name: "CHEMISTRY LAB", credits: 1, grade: "D", status: "PASS" },
      { code: "23LC0301", name: "ENGINEERING WORKSHOP", credits: 1.5, grade: "B", status: "PASS" },
      { code: "23LC0501", name: "COMPUTER PROGRAMMING LAB", credits: 1.5, grade: "E", status: "PASS" },
      { code: "23HM0002", name: "HEALTH AND WELLNESS, YOGA AND SPORTS", credits: 0.5, grade: "B", status: "PASS" }
    ]
  },
  "25G01A4326": {
    rollNumber: "25G01A4326",
    name: "C S PRAVALIKA",
    branch: "Artificial Intelligence (AI)",
    yearSem: "B.Tech I Year - I Semester",
    regulation: "R23",
    college: "Sri Venkatesa Perumal College of Engineering & Technology (AUTONOMOUS)",
    status: "PASSED",
    sgpa: 9.13,
    cgpa: 9.13,
    subjects: [
      { code: "23HM0001", name: "COMMUNICATIVE ENGLISH", credits: 2, grade: "A", status: "PASS" },
      { code: "23BS0005", name: "CHEMISTRY", credits: 3, grade: "B", status: "PASS" },
      { code: "23BS0001", name: "LINEAR ALGEBRA & CALCULUS", credits: 3, grade: "S", status: "PASS" },
      { code: "23ES0101", name: "BASIC CIVIL & MECHANICAL ENGINEERING", credits: 3, grade: "B", status: "PASS" },
      { code: "23ES0501", name: "INTRODUCTION TO PROGRAMMING", credits: 3, grade: "A", status: "PASS" },
      { code: "23LC0001", name: "COMMUNICATIVE ENGLISH LAB", credits: 1, grade: "S", status: "PASS" },
      { code: "23LC0004", name: "CHEMISTRY LAB", credits: 1, grade: "S", status: "PASS" },
      { code: "23LC0301", name: "ENGINEERING WORKSHOP", credits: 1.5, grade: "S", status: "PASS" },
      { code: "23LC0501", name: "COMPUTER PROGRAMMING LAB", credits: 1.5, grade: "S", status: "PASS" },
      { code: "23HM0002", name: "HEALTH AND WELLNESS, YOGA AND SPORTS", credits: 0.5, grade: "S", status: "PASS" }
    ]
  },
  "25G01A4327": {
    rollNumber: "25G01A4327",
    name: "CHADALAVADA YASASWINI",
    branch: "Artificial Intelligence (AI)",
    yearSem: "B.Tech I Year - I Semester",
    regulation: "R23",
    college: "Sri Venkatesa Perumal College of Engineering & Technology (AUTONOMOUS)",
    status: "PASSED",
    sgpa: 7.29,
    cgpa: 7.29,
    subjects: [
      { code: "23HM0001", name: "COMMUNICATIVE ENGLISH", credits: 2, grade: "D", status: "PASS" },
      { code: "23BS0005", name: "CHEMISTRY", credits: 3, grade: "C", status: "PASS" },
      { code: "23BS0001", name: "LINEAR ALGEBRA & CALCULUS", credits: 3, grade: "D", status: "PASS" },
      { code: "23ES0101", name: "BASIC CIVIL & MECHANICAL ENGINEERING", credits: 3, grade: "C", status: "PASS" },
      { code: "23ES0501", name: "INTRODUCTION TO PROGRAMMING", credits: 3, grade: "C", status: "PASS" },
      { code: "23LC0001", name: "COMMUNICATIVE ENGLISH LAB", credits: 1, grade: "A", status: "PASS" },
      { code: "23LC0004", name: "CHEMISTRY LAB", credits: 1, grade: "B", status: "PASS" },
      { code: "23LC0301", name: "ENGINEERING WORKSHOP", credits: 1.5, grade: "S", status: "PASS" },
      { code: "23LC0501", name: "COMPUTER PROGRAMMING LAB", credits: 1.5, grade: "B", status: "PASS" },
      { code: "23HM0002", name: "HEALTH AND WELLNESS, YOGA AND SPORTS", credits: 0.5, grade: "S", status: "PASS" }
    ]
  },
  "25G01A4329": {
    rollNumber: "25G01A4329",
    name: "CHINTHALAPUDI HARSHA VARDHAN",
    branch: "Artificial Intelligence (AI)",
    yearSem: "B.Tech I Year - I Semester",
    regulation: "R23",
    college: "Sri Venkatesa Perumal College of Engineering & Technology (AUTONOMOUS)",
    status: "PASSED",
    sgpa: 7.46,
    cgpa: 7.46,
    subjects: [
      { code: "23HM0001", name: "COMMUNICATIVE ENGLISH", credits: 2, grade: "A", status: "PASS" },
      { code: "23BS0005", name: "CHEMISTRY", credits: 3, grade: "E", status: "PASS" },
      { code: "23BS0001", name: "LINEAR ALGEBRA & CALCULUS", credits: 3, grade: "E", status: "PASS" },
      { code: "23ES0101", name: "BASIC CIVIL & MECHANICAL ENGINEERING", credits: 3, grade: "C", status: "PASS" },
      { code: "23ES0501", name: "INTRODUCTION TO PROGRAMMING", credits: 3, grade: "C", status: "PASS" },
      { code: "23LC0001", name: "COMMUNICATIVE ENGLISH LAB", credits: 1, grade: "B", status: "PASS" },
      { code: "23LC0004", name: "CHEMISTRY LAB", credits: 1, grade: "C", status: "PASS" },
      { code: "23LC0301", name: "ENGINEERING WORKSHOP", credits: 1.5, grade: "S", status: "PASS" },
      { code: "23LC0501", name: "COMPUTER PROGRAMMING LAB", credits: 1.5, grade: "A", status: "PASS" },
      { code: "23HM0002", name: "HEALTH AND WELLNESS, YOGA AND SPORTS", credits: 0.5, grade: "S", status: "PASS" }
    ]
  },
  "25G01A4330": {
    rollNumber: "25G01A4330",
    name: "CHITAMBALAM VAMSIKRISHNA",
    branch: "Artificial Intelligence (AI)",
    yearSem: "B.Tech I Year - I Semester",
    regulation: "R23",
    college: "Sri Venkatesa Perumal College of Engineering & Technology (AUTONOMOUS)",
    status: "FAILED",
    sgpa: 2.90,
    cgpa: 2.90,
    subjects: [
      { code: "23HM0001", name: "COMMUNICATIVE ENGLISH", credits: 0, grade: "F", status: "FAIL" },
      { code: "23BS0005", name: "CHEMISTRY", credits: 3, grade: "E", status: "PASS" },
      { code: "23BS0001", name: "LINEAR ALGEBRA & CALCULUS", credits: 0, grade: "F", status: "FAIL" },
      { code: "23ES0101", name: "BASIC CIVIL & MECHANICAL ENGINEERING", credits: 0, grade: "F", status: "FAIL" },
      { code: "23ES0501", name: "INTRODUCTION TO PROGRAMMING", credits: 0, grade: "F", status: "FAIL" },
      { code: "23LC0001", name: "COMMUNICATIVE ENGLISH LAB", credits: 1, grade: "C", status: "PASS" },
      { code: "23LC0004", name: "CHEMISTRY LAB", credits: 1, grade: "C", status: "PASS" },
      { code: "23LC0301", name: "ENGINEERING WORKSHOP", credits: 1.5, grade: "A", status: "PASS" },
      { code: "23LC0501", name: "COMPUTER PROGRAMMING LAB", credits: 1.5, grade: "D", status: "PASS" },
      { code: "23HM0002", name: "HEALTH AND WELLNESS, YOGA AND SPORTS", credits: 0.5, grade: "S", status: "PASS" }
    ]
  },
  "25G01A4331": {
    rollNumber: "25G01A4331",
    name: "CHITTEMREDDY RAJESH REDDY",
    branch: "Artificial Intelligence (AI)",
    yearSem: "B.Tech I Year - I Semester",
    regulation: "R23",
    college: "Sri Venkatesa Perumal College of Engineering & Technology (AUTONOMOUS)",
    status: "FAILED",
    sgpa: 5.72,
    cgpa: 5.72,
    subjects: [
      { code: "23HM0001", name: "COMMUNICATIVE ENGLISH", credits: 2, grade: "D", status: "PASS" },
      { code: "23BS0005", name: "CHEMISTRY", credits: 3, grade: "E", status: "PASS" },
      { code: "23BS0001", name: "LINEAR ALGEBRA & CALCULUS", credits: 3, grade: "E", status: "PASS" },
      { code: "23ES0101", name: "BASIC CIVIL & MECHANICAL ENGINEERING", credits: 3, grade: "C", status: "PASS" },
      { code: "23ES0501", name: "INTRODUCTION TO PROGRAMMING", credits: 0, grade: "F", status: "FAIL" },
      { code: "23LC0001", name: "COMMUNICATIVE ENGLISH LAB", credits: 1, grade: "B", status: "PASS" },
      { code: "23LC0004", name: "CHEMISTRY LAB", credits: 1, grade: "A", status: "PASS" },
      { code: "23LC0301", name: "ENGINEERING WORKSHOP", credits: 1.5, grade: "A", status: "PASS" },
      { code: "23LC0501", name: "COMPUTER PROGRAMMING LAB", credits: 1.5, grade: "A", status: "PASS" },
      { code: "23HM0002", name: "HEALTH AND WELLNESS, YOGA AND SPORTS", credits: 0.5, grade: "A", status: "PASS" }
    ]
  },
  "25G01A4332": {
    rollNumber: "25G01A4332",
    name: "CHITTOORU GEREESHMA",
    branch: "Artificial Intelligence (AI)",
    yearSem: "B.Tech I Year - I Semester",
    regulation: "R23",
    college: "Sri Venkatesa Perumal College of Engineering & Technology (AUTONOMOUS)",
    status: "FAILED",
    sgpa: 5.51,
    cgpa: 5.51,
    subjects: [
      { code: "23HM0001", name: "COMMUNICATIVE ENGLISH", credits: 2, grade: "D", status: "PASS" },
      { code: "23BS0005", name: "CHEMISTRY", credits: 3, grade: "D", status: "PASS" },
      { code: "23BS0001", name: "LINEAR ALGEBRA & CALCULUS", credits: 3, grade: "E", status: "PASS" },
      { code: "23ES0101", name: "BASIC CIVIL & MECHANICAL ENGINEERING", credits: 3, grade: "D", status: "PASS" },
      { code: "23ES0501", name: "INTRODUCTION TO PROGRAMMING", credits: 0, grade: "F", status: "FAIL" },
      { code: "23LC0001", name: "COMMUNICATIVE ENGLISH LAB", credits: 1, grade: "A", status: "PASS" },
      { code: "23LC0004", name: "CHEMISTRY LAB", credits: 1, grade: "C", status: "PASS" },
      { code: "23LC0301", name: "ENGINEERING WORKSHOP", credits: 1.5, grade: "A", status: "PASS" },
      { code: "23LC0501", name: "COMPUTER PROGRAMMING LAB", credits: 1.5, grade: "C", status: "PASS" },
      { code: "23HM0002", name: "HEALTH AND WELLNESS, YOGA AND SPORTS", credits: 0.5, grade: "A", status: "PASS" }
    ]
  },
  "25G01A4333": {
    rollNumber: "25G01A4333",
    name: "D SINDHU",
    branch: "Artificial Intelligence (AI)",
    yearSem: "B.Tech I Year - I Semester",
    regulation: "R23",
    college: "Sri Venkatesa Perumal College of Engineering & Technology (AUTONOMOUS)",
    status: "FAILED",
    sgpa: 3.92,
    cgpa: 3.92,
    subjects: [
      { code: "23HM0001", name: "COMMUNICATIVE ENGLISH", credits: 2, grade: "D", status: "PASS" },
      { code: "23BS0005", name: "CHEMISTRY", credits: 3, grade: "D", status: "PASS" },
      { code: "23BS0001", name: "LINEAR ALGEBRA & CALCULUS", credits: 0, grade: "F", status: "FAIL" },
      { code: "23ES0101", name: "BASIC CIVIL & MECHANICAL ENGINEERING", credits: 0, grade: "F", status: "FAIL" },
      { code: "23ES0501", name: "INTRODUCTION TO PROGRAMMING", credits: 0, grade: "F", status: "FAIL" },
      { code: "23LC0001", name: "COMMUNICATIVE ENGLISH LAB", credits: 1, grade: "B", status: "PASS" },
      { code: "23LC0004", name: "CHEMISTRY LAB", credits: 1, grade: "B", status: "PASS" },
      { code: "23LC0301", name: "ENGINEERING WORKSHOP", credits: 1.5, grade: "A", status: "PASS" },
      { code: "23LC0501", name: "COMPUTER PROGRAMMING LAB", credits: 1.5, grade: "B", status: "PASS" },
      { code: "23HM0002", name: "HEALTH AND WELLNESS, YOGA AND SPORTS", credits: 0.5, grade: "S", status: "PASS" }
    ]
  },
  "25G01A4334": {
    rollNumber: "25G01A4334",
    name: "DASARI PRAVEEN BABU",
    branch: "Artificial Intelligence (AI)",
    yearSem: "B.Tech I Year - I Semester",
    regulation: "R23",
    college: "Sri Venkatesa Perumal College of Engineering & Technology (AUTONOMOUS)",
    status: "PASSED",
    sgpa: 6.33,
    cgpa: 6.33,
    subjects: [
      { code: "23HM0001", name: "COMMUNICATIVE ENGLISH", credits: 2, grade: "D", status: "PASS" },
      { code: "23BS0005", name: "CHEMISTRY", credits: 3, grade: "E", status: "PASS" },
      { code: "23BS0001", name: "LINEAR ALGEBRA & CALCULUS", credits: 3, grade: "D", status: "PASS" },
      { code: "23ES0101", name: "BASIC CIVIL & MECHANICAL ENGINEERING", credits: 3, grade: "C", status: "PASS" },
      { code: "23ES0501", name: "INTRODUCTION TO PROGRAMMING", credits: 3, grade: "D", status: "PASS" },
      { code: "23LC0001", name: "COMMUNICATIVE ENGLISH LAB", credits: 1, grade: "C", status: "PASS" },
      { code: "23LC0004", name: "CHEMISTRY LAB", credits: 1, grade: "C", status: "PASS" },
      { code: "23LC0301", name: "ENGINEERING WORKSHOP", credits: 1.5, grade: "B", status: "PASS" },
      { code: "23LC0501", name: "COMPUTER PROGRAMMING LAB", credits: 1.5, grade: "D", status: "PASS" },
      { code: "23HM0002", name: "HEALTH AND WELLNESS, YOGA AND SPORTS", credits: 0.5, grade: "A", status: "PASS" }
    ]
  },
  "25G01A4335": {
    rollNumber: "25G01A4335",
    name: "DEVALLA GUNASRI",
    branch: "Artificial Intelligence (AI)",
    yearSem: "B.Tech I Year - I Semester",
    regulation: "R23",
    college: "Sri Venkatesa Perumal College of Engineering & Technology (AUTONOMOUS)",
    status: "PASSED",
    sgpa: 6.44,
    cgpa: 6.44,
    subjects: [
      { code: "23HM0001", name: "COMMUNICATIVE ENGLISH", credits: 2, grade: "D", status: "PASS" },
      { code: "23BS0005", name: "CHEMISTRY", credits: 3, grade: "E", status: "PASS" },
      { code: "23BS0001", name: "LINEAR ALGEBRA & CALCULUS", credits: 3, grade: "E", status: "PASS" },
      { code: "23ES0101", name: "BASIC CIVIL & MECHANICAL ENGINEERING", credits: 3, grade: "D", status: "PASS" },
      { code: "23ES0501", name: "INTRODUCTION TO PROGRAMMING", credits: 3, grade: "D", status: "PASS" },
      { code: "23LC0001", name: "COMMUNICATIVE ENGLISH LAB", credits: 1, grade: "A", status: "PASS" },
      { code: "23LC0004", name: "CHEMISTRY LAB", credits: 1, grade: "B", status: "PASS" },
      { code: "23LC0301", name: "ENGINEERING WORKSHOP", credits: 1.5, grade: "S", status: "PASS" },
      { code: "23LC0501", name: "COMPUTER PROGRAMMING LAB", credits: 1.5, grade: "C", status: "PASS" },
      { code: "23HM0002", name: "HEALTH AND WELLNESS, YOGA AND SPORTS", credits: 0.5, grade: "S", status: "PASS" }
    ]
  },
  "25G01A4336": {
    rollNumber: "25G01A4336",
    name: "DEVARAKONDA MOHITH",
    branch: "Artificial Intelligence (AI)",
    yearSem: "B.Tech I Year - I Semester",
    regulation: "R23",
    college: "Sri Venkatesa Perumal College of Engineering & Technology (AUTONOMOUS)",
    status: "FAILED",
    sgpa: 1.03,
    cgpa: 1.03,
    subjects: [
      { code: "23HM0001", name: "COMMUNICATIVE ENGLISH", credits: 2, grade: "E", status: "PASS" },
      { code: "23BS0005", name: "CHEMISTRY", credits: 0, grade: "F", status: "FAIL" },
      { code: "23BS0001", name: "LINEAR ALGEBRA & CALCULUS", credits: 0, grade: "F", status: "FAIL" },
      { code: "23ES0101", name: "BASIC CIVIL & MECHANICAL ENGINEERING", credits: 0, grade: "F", status: "FAIL" },
      { code: "23ES0501", name: "INTRODUCTION TO PROGRAMMING", credits: 0, grade: "F", status: "FAIL" },
      { code: "23LC0001", name: "COMMUNICATIVE ENGLISH LAB", credits: 0, grade: "-Ab-", status: "FAIL" },
      { code: "23LC0004", name: "CHEMISTRY LAB", credits: 1, grade: "D", status: "PASS" },
      { code: "23LC0301", name: "ENGINEERING WORKSHOP", credits: 0, grade: "-Ab-", status: "FAIL" },
      { code: "23LC0501", name: "COMPUTER PROGRAMMING LAB", credits: 0, grade: "-Ab-", status: "FAIL" },
      { code: "23HM0002", name: "HEALTH AND WELLNESS, YOGA AND SPORTS", credits: 0.5, grade: "B", status: "PASS" }
    ]
  },
  "25G01A4337": {
    rollNumber: "25G01A4337",
    name: "DHANTLA HARIKA",
    branch: "Artificial Intelligence (AI)",
    yearSem: "B.Tech I Year - I Semester",
    regulation: "R23",
    college: "Sri Venkatesa Perumal College of Engineering & Technology (AUTONOMOUS)",
    status: "PASSED",
    sgpa: 7.64,
    cgpa: 7.64,
    subjects: [
      { code: "23HM0001", name: "COMMUNICATIVE ENGLISH", credits: 2, grade: "C", status: "PASS" },
      { code: "23BS0005", name: "CHEMISTRY", credits: 3, grade: "C", status: "PASS" },
      { code: "23BS0001", name: "LINEAR ALGEBRA & CALCULUS", credits: 3, grade: "C", status: "PASS" },
      { code: "23ES0101", name: "BASIC CIVIL & MECHANICAL ENGINEERING", credits: 3, grade: "C", status: "PASS" },
      { code: "23ES0501", name: "INTRODUCTION TO PROGRAMMING", credits: 3, grade: "C", status: "PASS" },
      { code: "23LC0001", name: "COMMUNICATIVE ENGLISH LAB", credits: 1, grade: "A", status: "PASS" },
      { code: "23LC0004", name: "CHEMISTRY LAB", credits: 1, grade: "A", status: "PASS" },
      { code: "23LC0301", name: "ENGINEERING WORKSHOP", credits: 1.5, grade: "S", status: "PASS" },
      { code: "23LC0501", name: "COMPUTER PROGRAMMING LAB", credits: 1.5, grade: "A", status: "PASS" },
      { code: "23HM0002", name: "HEALTH AND WELLNESS, YOGA AND SPORTS", credits: 0.5, grade: "A", status: "PASS" }
    ]
  },
  "25G01A4338": {
    rollNumber: "25G01A4338",
    name: "DONGARA VENU",
    branch: "Artificial Intelligence (AI)",
    yearSem: "B.Tech I Year - I Semester",
    regulation: "R23",
    college: "Sri Venkatesa Perumal College of Engineering & Technology (AUTONOMOUS)",
    status: "FAILED",
    sgpa: 1.36,
    cgpa: 1.36,
    subjects: [
      { code: "23HM0001", name: "COMMUNICATIVE ENGLISH", credits: 0, grade: "F", status: "FAIL" },
      { code: "23BS0005", name: "CHEMISTRY", credits: 0, grade: "F", status: "FAIL" },
      { code: "23BS0001", name: "LINEAR ALGEBRA & CALCULUS", credits: 0, grade: "F", status: "FAIL" },
      { code: "23ES0101", name: "BASIC CIVIL & MECHANICAL ENGINEERING", credits: 0, grade: "F", status: "FAIL" },
      { code: "23ES0501", name: "INTRODUCTION TO PROGRAMMING", credits: 0, grade: "F", status: "FAIL" },
      { code: "23LC0001", name: "COMMUNICATIVE ENGLISH LAB", credits: 1, grade: "D", status: "PASS" },
      { code: "23LC0004", name: "CHEMISTRY LAB", credits: 1, grade: "D", status: "PASS" },
      { code: "23LC0301", name: "ENGINEERING WORKSHOP", credits: 1.5, grade: "C", status: "PASS" },
      { code: "23LC0501", name: "COMPUTER PROGRAMMING LAB", credits: 0, grade: "-Ab-", status: "FAIL" },
      { code: "23HM0002", name: "HEALTH AND WELLNESS, YOGA AND SPORTS", credits: 0.5, grade: "B", status: "PASS" }
    ]
  },
  "25G01A4339": {
    rollNumber: "25G01A4339",
    name: "DUDEKULA BASHEER",
    branch: "Artificial Intelligence (AI)",
    yearSem: "B.Tech I Year - I Semester",
    regulation: "R23",
    college: "Sri Venkatesa Perumal College of Engineering & Technology (AUTONOMOUS)",
    status: "FAILED",
    sgpa: 5.49,
    cgpa: 5.49,
    subjects: [
      { code: "23HM0001", name: "COMMUNICATIVE ENGLISH", credits: 2, grade: "C", status: "PASS" },
      { code: "23BS0005", name: "CHEMISTRY", credits: 3, grade: "D", status: "PASS" },
      { code: "23BS0001", name: "LINEAR ALGEBRA & CALCULUS", credits: 3, grade: "E", status: "PASS" },
      { code: "23ES0101", name: "BASIC CIVIL & MECHANICAL ENGINEERING", credits: 3, grade: "D", status: "PASS" },
      { code: "23ES0501", name: "INTRODUCTION TO PROGRAMMING", credits: 0, grade: "F", status: "FAIL" },
      { code: "23LC0001", name: "COMMUNICATIVE ENGLISH LAB", credits: 1, grade: "C", status: "PASS" },
      { code: "23LC0004", name: "CHEMISTRY LAB", credits: 1, grade: "C", status: "PASS" },
      { code: "23LC0301", name: "ENGINEERING WORKSHOP", credits: 1.5, grade: "A", status: "PASS" },
      { code: "23LC0501", name: "COMPUTER PROGRAMMING LAB", credits: 1.5, grade: "C", status: "PASS" },
      { code: "23HM0002", name: "HEALTH AND WELLNESS, YOGA AND SPORTS", credits: 0.5, grade: "B", status: "PASS" }
    ]
  },
  "25G01A4340": {
    rollNumber: "25G01A4340",
    name: "DUGGULURU SPANDANA",
    branch: "Artificial Intelligence (AI)",
    yearSem: "B.Tech I Year - I Semester",
    regulation: "R23",
    college: "Sri Venkatesa Perumal College of Engineering & Technology (AUTONOMOUS)",
    status: "FAILED",
    sgpa: 2.05,
    cgpa: 2.05,
    subjects: [
      { code: "23HM0001", name: "COMMUNICATIVE ENGLISH", credits: 2, grade: "E", status: "PASS" },
      { code: "23BS0005", name: "CHEMISTRY", credits: 0, grade: "F", status: "FAIL" },
      { code: "23BS0001", name: "LINEAR ALGEBRA & CALCULUS", credits: 0, grade: "F", status: "FAIL" },
      { code: "23ES0101", name: "BASIC CIVIL & MECHANICAL ENGINEERING", credits: 0, grade: "F", status: "FAIL" },
      { code: "23ES0501", name: "INTRODUCTION TO PROGRAMMING", credits: 0, grade: "F", status: "FAIL" },
      { code: "23LC0001", name: "COMMUNICATIVE ENGLISH LAB", credits: 1, grade: "B", status: "PASS" },
      { code: "23LC0004", name: "CHEMISTRY LAB", credits: 1, grade: "D", status: "PASS" },
      { code: "23LC0301", name: "ENGINEERING WORKSHOP", credits: 1.5, grade: "B", status: "PASS" },
      { code: "23LC0501", name: "COMPUTER PROGRAMMING LAB", credits: 0, grade: "-Ab-", status: "FAIL" },
      { code: "23HM0002", name: "HEALTH AND WELLNESS, YOGA AND SPORTS", credits: 0.5, grade: "B", status: "PASS" }
    ]
  },
  "25G01A4341": {
    rollNumber: "25G01A4341",
    name: "E RUSHITHA",
    branch: "Artificial Intelligence (AI)",
    yearSem: "B.Tech I Year - I Semester",
    regulation: "R23",
    college: "Sri Venkatesa Perumal College of Engineering & Technology (AUTONOMOUS)",
    status: "FAILED",
    sgpa: 6.69,
    cgpa: 6.69,
    subjects: [
      { code: "23HM0001", name: "COMMUNICATIVE ENGLISH", credits: 2, grade: "D", status: "PASS" },
      { code: "23BS0005", name: "CHEMISTRY", credits: 3, grade: "D", status: "PASS" },
      { code: "23BS0001", name: "LINEAR ALGEBRA & CALCULUS", credits: 3, grade: "A", status: "PASS" },
      { code: "23ES0101", name: "BASIC CIVIL & MECHANICAL ENGINEERING", credits: 3, grade: "C", status: "PASS" },
      { code: "23ES0501", name: "INTRODUCTION TO PROGRAMMING", credits: 0, grade: "F", status: "FAIL" },
      { code: "23LC0001", name: "COMMUNICATIVE ENGLISH LAB", credits: 1, grade: "A", status: "PASS" },
      { code: "23LC0004", name: "CHEMISTRY LAB", credits: 1, grade: "S", status: "PASS" },
      { code: "23LC0301", name: "ENGINEERING WORKSHOP", credits: 1.5, grade: "S", status: "PASS" },
      { code: "23LC0501", name: "COMPUTER PROGRAMMING LAB", credits: 1.5, grade: "A", status: "PASS" },
      { code: "23HM0002", name: "HEALTH AND WELLNESS, YOGA AND SPORTS", credits: 0.5, grade: "S", status: "PASS" }
    ]
  },
  "25G01A4342": {
    rollNumber: "25G01A4342",
    name: "G CHETHAN",
    branch: "Artificial Intelligence (AI)",
    yearSem: "B.Tech I Year - I Semester",
    regulation: "R23",
    college: "Sri Venkatesa Perumal College of Engineering & Technology (AUTONOMOUS)",
    status: "PASSED",
    sgpa: 9.28,
    cgpa: 9.28,
    subjects: [
      { code: "23HM0001", name: "COMMUNICATIVE ENGLISH", credits: 2, grade: "A", status: "PASS" },
      { code: "23BS0005", name: "CHEMISTRY", credits: 3, grade: "A", status: "PASS" },
      { code: "23BS0001", name: "LINEAR ALGEBRA & CALCULUS", credits: 3, grade: "S", status: "PASS" },
      { code: "23ES0101", name: "BASIC CIVIL & MECHANICAL ENGINEERING", credits: 3, grade: "B", status: "PASS" },
      { code: "23ES0501", name: "INTRODUCTION TO PROGRAMMING", credits: 3, grade: "A", status: "PASS" },
      { code: "23LC0001", name: "COMMUNICATIVE ENGLISH LAB", credits: 1, grade: "S", status: "PASS" },
      { code: "23LC0004", name: "CHEMISTRY LAB", credits: 1, grade: "S", status: "PASS" },
      { code: "23LC0301", name: "ENGINEERING WORKSHOP", credits: 1.5, grade: "S", status: "PASS" },
      { code: "23LC0501", name: "COMPUTER PROGRAMMING LAB", credits: 1.5, grade: "S", status: "PASS" },
      { code: "23HM0002", name: "HEALTH AND WELLNESS, YOGA AND SPORTS", credits: 0.5, grade: "S", status: "PASS" }
    ]
  },
  "25G01A4343": {
    rollNumber: "25G01A4343",
    name: "GAJJAPPAGARI SIDDARTHA",
    branch: "Artificial Intelligence (AI)",
    yearSem: "B.Tech I Year - I Semester",
    regulation: "R23",
    college: "Sri Venkatesa Perumal College of Engineering & Technology (AUTONOMOUS)",
    status: "FAILED",
    sgpa: 2.54,
    cgpa: 2.54,
    subjects: [
      { code: "23HM0001", name: "COMMUNICATIVE ENGLISH", credits: 0, grade: "F", status: "FAIL" },
      { code: "23BS0005", name: "CHEMISTRY", credits: 0, grade: "F", status: "FAIL" },
      { code: "23BS0001", name: "LINEAR ALGEBRA & CALCULUS", credits: 3, grade: "E", status: "PASS" },
      { code: "23ES0101", name: "BASIC CIVIL & MECHANICAL ENGINEERING", credits: 0, grade: "F", status: "FAIL" },
      { code: "23ES0501", name: "INTRODUCTION TO PROGRAMMING", credits: 0, grade: "F", status: "FAIL" },
      { code: "23LC0001", name: "COMMUNICATIVE ENGLISH LAB", credits: 1, grade: "B", status: "PASS" },
      { code: "23LC0004", name: "CHEMISTRY LAB", credits: 1, grade: "B", status: "PASS" },
      { code: "23LC0301", name: "ENGINEERING WORKSHOP", credits: 1.5, grade: "A", status: "PASS" },
      { code: "23LC0501", name: "COMPUTER PROGRAMMING LAB", credits: 0, grade: "-Ab-", status: "FAIL" },
      { code: "23HM0002", name: "HEALTH AND WELLNESS, YOGA AND SPORTS", credits: 0.5, grade: "S", status: "PASS" }
    ]
  },
  "25G01A4344": {
    rollNumber: "25G01A4344",
    name: "GANAPARTHI MOUNIKA",
    branch: "Artificial Intelligence (AI)",
    yearSem: "B.Tech I Year - I Semester",
    regulation: "R23",
    college: "Sri Venkatesa Perumal College of Engineering & Technology (AUTONOMOUS)",
    status: "FAILED",
    sgpa: 2.28,
    cgpa: 2.28,
    subjects: [
      { code: "23HM0001", name: "COMMUNICATIVE ENGLISH", credits: 0, grade: "F", status: "FAIL" },
      { code: "23BS0005", name: "CHEMISTRY", credits: 0, grade: "F", status: "FAIL" },
      { code: "23BS0001", name: "LINEAR ALGEBRA & CALCULUS", credits: 3, grade: "E", status: "PASS" },
      { code: "23ES0101", name: "BASIC CIVIL & MECHANICAL ENGINEERING", credits: 0, grade: "F", status: "FAIL" },
      { code: "23ES0501", name: "INTRODUCTION TO PROGRAMMING", credits: 0, grade: "F", status: "FAIL" },
      { code: "23LC0001", name: "COMMUNICATIVE ENGLISH LAB", credits: 1, grade: "D", status: "PASS" },
      { code: "23LC0004", name: "CHEMISTRY LAB", credits: 1, grade: "D", status: "PASS" },
      { code: "23LC0301", name: "ENGINEERING WORKSHOP", credits: 1.5, grade: "A", status: "PASS" },
      { code: "23LC0501", name: "COMPUTER PROGRAMMING LAB", credits: 0, grade: "-Ab-", status: "FAIL" },
      { code: "23HM0002", name: "HEALTH AND WELLNESS, YOGA AND SPORTS", credits: 0.5, grade: "B", status: "PASS" }
    ]
  },
  "25G01A4345": {
    rollNumber: "25G01A4345",
    name: "GANGA RANGA SWAMY",
    branch: "Artificial Intelligence (AI)",
    yearSem: "B.Tech I Year - I Semester",
    regulation: "R23",
    college: "Sri Venkatesa Perumal College of Engineering & Technology (AUTONOMOUS)",
    status: "FAILED",
    sgpa: 5.21,
    cgpa: 5.21,
    subjects: [
      { code: "23HM0001", name: "COMMUNICATIVE ENGLISH", credits: 0, grade: "F", status: "FAIL" },
      { code: "23BS0005", name: "CHEMISTRY", credits: 3, grade: "D", status: "PASS" },
      { code: "23BS0001", name: "LINEAR ALGEBRA & CALCULUS", credits: 3, grade: "D", status: "PASS" },
      { code: "23ES0101", name: "BASIC CIVIL & MECHANICAL ENGINEERING", credits: 0, grade: "F", status: "FAIL" },
      { code: "23ES0501", name: "INTRODUCTION TO PROGRAMMING", credits: 3, grade: "D", status: "PASS" },
      { code: "23LC0001", name: "COMMUNICATIVE ENGLISH LAB", credits: 1, grade: "C", status: "PASS" },
      { code: "23LC0004", name: "CHEMISTRY LAB", credits: 1, grade: "A", status: "PASS" },
      { code: "23LC0301", name: "ENGINEERING WORKSHOP", credits: 1.5, grade: "S", status: "PASS" },
      { code: "23LC0501", name: "COMPUTER PROGRAMMING LAB", credits: 1.5, grade: "B", status: "PASS" },
      { code: "23HM0002", name: "HEALTH AND WELLNESS, YOGA AND SPORTS", credits: 0.5, grade: "A", status: "PASS" }
    ]
  },
  "25G01A4346": {
    rollNumber: "25G01A4346",
    name: "GANJI JASVANTH REDDY",
    branch: "Artificial Intelligence (AI)",
    yearSem: "B.Tech I Year - I Semester",
    regulation: "R23",
    college: "Sri Venkatesa Perumal College of Engineering & Technology (AUTONOMOUS)",
    status: "FAILED",
    sgpa: 2.90,
    cgpa: 2.90,
    subjects: [
      { code: "23HM0001", name: "COMMUNICATIVE ENGLISH", credits: 0, grade: "F", status: "FAIL" },
      { code: "23BS0005", name: "CHEMISTRY", credits: 0, grade: "F", status: "FAIL" },
      { code: "23BS0001", name: "LINEAR ALGEBRA & CALCULUS", credits: 3, grade: "E", status: "PASS" },
      { code: "23ES0101", name: "BASIC CIVIL & MECHANICAL ENGINEERING", credits: 0, grade: "F", status: "FAIL" },
      { code: "23ES0501", name: "INTRODUCTION TO PROGRAMMING", credits: 0, grade: "F", status: "FAIL" },
      { code: "23LC0001", name: "COMMUNICATIVE ENGLISH LAB", credits: 1, grade: "B", status: "PASS" },
      { code: "23LC0004", name: "CHEMISTRY LAB", credits: 1, grade: "D", status: "PASS" },
      { code: "23LC0301", name: "ENGINEERING WORKSHOP", credits: 1.5, grade: "A", status: "PASS" },
      { code: "23LC0501", name: "COMPUTER PROGRAMMING LAB", credits: 1.5, grade: "D", status: "PASS" },
      { code: "23HM0002", name: "HEALTH AND WELLNESS, YOGA AND SPORTS", credits: 0.5, grade: "S", status: "PASS" }
    ]
  },
  "25G01A4347": {
    rollNumber: "25G01A4347",
    name: "GATTU DHANUSH",
    branch: "Artificial Intelligence (AI)",
    yearSem: "B.Tech I Year - I Semester",
    regulation: "R23",
    college: "Sri Venkatesa Perumal College of Engineering & Technology (AUTONOMOUS)",
    status: "PASSED",
    sgpa: 8.05,
    cgpa: 8.05,
    subjects: [
      { code: "23HM0001", name: "COMMUNICATIVE ENGLISH", credits: 2, grade: "C", status: "PASS" },
      { code: "23BS0005", name: "CHEMISTRY", credits: 3, grade: "B", status: "PASS" },
      { code: "23BS0001", name: "LINEAR ALGEBRA & CALCULUS", credits: 3, grade: "A", status: "PASS" },
      { code: "23ES0101", name: "BASIC CIVIL & MECHANICAL ENGINEERING", credits: 3, grade: "D", status: "PASS" },
      { code: "23ES0501", name: "INTRODUCTION TO PROGRAMMING", credits: 3, grade: "B", status: "PASS" },
      { code: "23LC0001", name: "COMMUNICATIVE ENGLISH LAB", credits: 1, grade: "A", status: "PASS" },
      { code: "23LC0004", name: "CHEMISTRY LAB", credits: 1, grade: "A", status: "PASS" },
      { code: "23LC0301", name: "ENGINEERING WORKSHOP", credits: 1.5, grade: "S", status: "PASS" },
      { code: "23LC0501", name: "COMPUTER PROGRAMMING LAB", credits: 1.5, grade: "B", status: "PASS" },
      { code: "23HM0002", name: "HEALTH AND WELLNESS, YOGA AND SPORTS", credits: 0.5, grade: "S", status: "PASS" }
    ]
  },
  "25G01A4348": {
    rollNumber: "25G01A4348",
    name: "GIDDALURU GANGA VYSHNAVI",
    branch: "Artificial Intelligence (AI)",
    yearSem: "B.Tech I Year - I Semester",
    regulation: "R23",
    college: "Sri Venkatesa Perumal College of Engineering & Technology (AUTONOMOUS)",
    status: "FAILED",
    sgpa: 2.33,
    cgpa: 2.33,
    subjects: [
      { code: "23HM0001", name: "COMMUNICATIVE ENGLISH", credits: 0, grade: "F", status: "FAIL" },
      { code: "23BS0005", name: "CHEMISTRY", credits: 0, grade: "F", status: "FAIL" },
      { code: "23BS0001", name: "LINEAR ALGEBRA & CALCULUS", credits: 3, grade: "E", status: "PASS" },
      { code: "23ES0101", name: "BASIC CIVIL & MECHANICAL ENGINEERING", credits: 0, grade: "F", status: "FAIL" },
      { code: "23ES0501", name: "INTRODUCTION TO PROGRAMMING", credits: 0, grade: "F", status: "FAIL" },
      { code: "23LC0001", name: "COMMUNICATIVE ENGLISH LAB", credits: 1, grade: "C", status: "PASS" },
      { code: "23LC0004", name: "CHEMISTRY LAB", credits: 1, grade: "D", status: "PASS" },
      { code: "23LC0301", name: "ENGINEERING WORKSHOP", credits: 1.5, grade: "A", status: "PASS" },
      { code: "23LC0501", name: "COMPUTER PROGRAMMING LAB", credits: 0, grade: "-Ab-", status: "FAIL" },
      { code: "23HM0002", name: "HEALTH AND WELLNESS, YOGA AND SPORTS", credits: 0.5, grade: "B", status: "PASS" }
    ]
  },
  "25G01A4349": {
    rollNumber: "25G01A4349",
    name: "GUDE HARSHITHA",
    branch: "Artificial Intelligence (AI)",
    yearSem: "B.Tech I Year - I Semester",
    regulation: "R23",
    college: "Sri Venkatesa Perumal College of Engineering & Technology (AUTONOMOUS)",
    status: "PASSED",
    sgpa: 6.92,
    cgpa: 6.92,
    subjects: [
      { code: "23HM0001", name: "COMMUNICATIVE ENGLISH", credits: 2, grade: "D", status: "PASS" },
      { code: "23BS0005", name: "CHEMISTRY", credits: 3, grade: "E", status: "PASS" },
      { code: "23BS0001", name: "LINEAR ALGEBRA & CALCULUS", credits: 3, grade: "B", status: "PASS" },
      { code: "23ES0101", name: "BASIC CIVIL & MECHANICAL ENGINEERING", credits: 3, grade: "C", status: "PASS" },
      { code: "23ES0501", name: "INTRODUCTION TO PROGRAMMING", credits: 3, grade: "C", status: "PASS" },
      { code: "23LC0001", name: "COMMUNICATIVE ENGLISH LAB", credits: 1, grade: "C", status: "PASS" },
      { code: "23LC0004", name: "CHEMISTRY LAB", credits: 1, grade: "B", status: "PASS" },
      { code: "23LC0301", name: "ENGINEERING WORKSHOP", credits: 1.5, grade: "A", status: "PASS" },
      { code: "23LC0501", name: "COMPUTER PROGRAMMING LAB", credits: 1.5, grade: "D", status: "PASS" },
      { code: "23HM0002", name: "HEALTH AND WELLNESS, YOGA AND SPORTS", credits: 0.5, grade: "A", status: "PASS" }
    ]
  },
  "25G01A4350": {
    rollNumber: "25G01A4350",
    name: "GATTU DHANUSH",
    branch: "Artificial Intelligence (AI)",
    yearSem: "B.Tech I Year - I Semester",
    regulation: "R23",
    college: "Sri Venkatesa Perumal College of Engineering & Technology (AUTONOMOUS)",
    status: "FAILED",
    sgpa: 4.59,
    cgpa: 4.59,
    subjects: [
      { code: "23HM0001", name: "COMMUNICATIVE ENGLISH", credits: 0, grade: "F", status: "FAIL" },
      { code: "23BS0005", name: "CHEMISTRY", credits: 3, grade: "E", status: "PASS" },
      { code: "23BS0001", name: "LINEAR ALGEBRA & CALCULUS", credits: 3, grade: "E", status: "PASS" },
      { code: "23ES0101", name: "BASIC CIVIL & MECHANICAL ENGINEERING", credits: 3, grade: "D", status: "PASS" },
      { code: "23ES0501", name: "INTRODUCTION TO PROGRAMMING", credits: 0, grade: "F", status: "FAIL" },
      { code: "23LC0001", name: "COMMUNICATIVE ENGLISH LAB", credits: 1, grade: "D", status: "PASS" },
      { code: "23LC0004", name: "CHEMISTRY LAB", credits: 1, grade: "C", status: "PASS" },
      { code: "23LC0301", name: "ENGINEERING WORKSHOP", credits: 1.5, grade: "A", status: "PASS" },
      { code: "23LC0501", name: "COMPUTER PROGRAMMING LAB", credits: 1.5, grade: "C", status: "PASS" },
      { code: "23HM0002", name: "HEALTH AND WELLNESS, YOGA AND SPORTS", credits: 0.5, grade: "A", status: "PASS" }
    ]
  },
  "25G01A4351": {
    rollNumber: "25G01A4351",
    name: "GIDDALURU GANGA VYSHNAVI",
    branch: "Artificial Intelligence (AI)",
    yearSem: "B.Tech I Year - I Semester",
    regulation: "R23",
    college: "Sri Venkatesa Perumal College of Engineering & Technology (AUTONOMOUS)",
    status: "FAILED",
    sgpa: 6.33,
    cgpa: 6.33,
    subjects: [
      { code: "23HM0001", name: "COMMUNICATIVE ENGLISH", credits: 0, grade: "F", status: "FAIL" },
      { code: "23BS0005", name: "CHEMISTRY", credits: 3, grade: "D", status: "PASS" },
      { code: "23BS0001", name: "LINEAR ALGEBRA & CALCULUS", credits: 3, grade: "D", status: "PASS" },
      { code: "23ES0101", name: "BASIC CIVIL & MECHANICAL ENGINEERING", credits: 3, grade: "C", status: "PASS" },
      { code: "23ES0501", name: "INTRODUCTION TO PROGRAMMING", credits: 3, grade: "C", status: "PASS" },
      { code: "23LC0001", name: "COMMUNICATIVE ENGLISH LAB", credits: 1, grade: "A", status: "PASS" },
      { code: "23LC0004", name: "CHEMISTRY LAB", credits: 1, grade: "B", status: "PASS" },
      { code: "23LC0301", name: "ENGINEERING WORKSHOP", credits: 1.5, grade: "A", status: "PASS" },
      { code: "23LC0501", name: "COMPUTER PROGRAMMING LAB", credits: 1.5, grade: "C", status: "PASS" },
      { code: "23HM0002", name: "HEALTH AND WELLNESS, YOGA AND SPORTS", credits: 0.5, grade: "A", status: "PASS" }
    ]
  },
  "25G01A4352": {
    rollNumber: "25G01A4352",
    name: "GUDE HARSHITHA",
    branch: "Artificial Intelligence (AI)",
    yearSem: "B.Tech I Year - I Semester",
    regulation: "R23",
    college: "Sri Venkatesa Perumal College of Engineering & Technology (AUTONOMOUS)",
    status: "FAILED",
    sgpa: 0,
    cgpa: 0,
    subjects: [
      { code: "23HM0001", name: "COMMUNICATIVE ENGLISH", credits: 2, grade: "D", status: "PASS" },
      { code: "23BS0005", name: "CHEMISTRY", credits: 3, grade: "D", status: "PASS" },
      { code: "23BS0001", name: "LINEAR ALGEBRA & CALCULUS", credits: 3, grade: "E", status: "PASS" },
      { code: "23ES0101", name: "BASIC CIVIL & MECHANICAL ENGINEERING", credits: 3, grade: "C", status: "PASS" },
      { code: "23ES0501", name: "INTRODUCTION TO PROGRAMMING", credits: 0, grade: "F", status: "FAIL" },
      { code: "23LC0001", name: "COMMUNICATIVE ENGLISH LAB", credits: 1, grade: "S", status: "PASS" },
      { code: "23LC0004", name: "CHEMISTRY LAB", credits: 1, grade: "D", status: "PASS" },
      { code: "23LC0301", name: "ENGINEERING WORKSHOP", credits: 1.5, grade: "A", status: "PASS" },
      { code: "23LC0501", name: "COMPUTER PROGRAMMING LAB", credits: 1.5, grade: "C", status: "PASS" }
    ]
  }
};